[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chatdatalab"
version = "0.1.0"
description = "A short description"
requires-python = ">=3.7"